#define MIE_SSIE (1 << 0)
#define MIE_MSIE (1 << 1)
#define MIE_STIE (1 << 3)
#define MIE_MTIE (1 << 5)
#define MIE_SEIE (1 << 7)
#define MIE_MEIE (1 << 9)
#define MIE_LCOFIE (1 << 11)

#define MIP_SSIP (1 << 0)
#define MIP_MSIP (1 << 1)
#define MIP_STIP (1 << 3)
#define MIP_MTIP (1 << 5)
#define MIP_SEIP (1 << 7)
#define MIP_MEIP (1 << 9)

#define SIP_SSIE (1 << 0)
#define SIP_SSIP (1 << 0)
#define SIP_STIP (1 << 8)
#define SIP_SEIP (1 << 11)
#define SIP_LCOFIP (1 << 13)

#define SIE_SSIE (1 << 0)
#define SIE_STIE (1 << 8)
#define SIE_SEIE (1 << 11)
#define SIE_LCOFIE (1 << 13)
#define MIP_LCOFIP (1 << 11)
